PLIP 9327: unified interface for lists of content
=================================================

PLIP ticket: http://dev.plone.org/plone/ticket/9327

Review by Ross Patterson (me@rpatterson.net, zenwryly on irc)

The PLIP was reviewed on Ubuntu 11.04 (Natty) using python 2.6.6
and Google Chrome 14.0.


Review steps
------------

- Ran the plips/plip9327-contentlisting.cfg buildout.

- Ran "bin/test -s plone.app.contentlisting -s Products.CMFPlone"  TODO

- Ran bin/alltests. TODO

- Created a new Plone site and added an event for checking collection
  views.  TODO

- Checked the following URLs:  TODO

  http://localhost:8080/Plone/folder_contents
  http://localhost:8080/Plone/folder_listing
  http://localhost:8080/Plone/events/aggregator
  http://localhost:8080/Plone/events/aggregator/folder_contents
  http://localhost:8080/Plone/events/aggregator/folder_listing

- Examined code.


Notes and observations
----------------------

- Noting the changes in
  Products/CMFPlone/skins/plone_content/folder_listing.pt
  (revisions 49150 and 49246):
    - does the change to item/ContentTypeClass work when the contents
      are normal brains or full objects as folder_listing is supposed
      to support?
    - does the change to item/review_state work when the contents are
      full objects as folder_listing is supposed to support?

- In plone.app.contentlisting/README.txt:
  - "python:context.folderListing(Type='Page')", is folderListing
    really a method of content objects?
  - "Getting a contentlisting directly from a template"  and "Usage
    example directly from a template" are still empty.

- Running the tests or firing up the instance produces the following
  error:

  Traceback (most recent call last):
  ...
    File "/home/xen/src/plone-coredev.svn/src/plone.app.upgrade/plone/app/upgrade/v40/__init__.py", line 2, in <module>
      import betas
    File "/home/xen/src/plone-coredev.svn/src/plone.app.upgrade/plone/app/upgrade/v40/betas.py", line 4, in <module>
      from Products.CMFPlone.CatalogTool import BLACKLISTED_INTERFACES
  ...
      ImportError: cannot import name BLACKLISTED_INTERFACES  

  I'm guessing the branch needs to have recent changes to trunk merged.

TODO I can't finish the review until this is fixed.

- "bin/instance fg" fails with the following.  Fixed by removing the
  instance:zcml option in the buildout and letting z3c.autoinclude
  handle it:

  zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.ModifyPortalContent')
    in:
    File "/home/xen/src/plone-coredev.svn/src/plone.app.layout/plone/app/layout/viewlets/configure.zcml", line 319.4-325.10
        <browser:viewlet
            name="plone.lockinfo"
            manager=".interfaces.IAboveContent"
            class="plone.locking.browser.info.LockInfoViewlet"
            permission="cmf.ModifyPortalContent"
            for="plone.locking.interfaces.ITTWLockable"
            />

- Test coverage is not 100% but looks pretty complete.

- I note that plone.app.contentlisting doesn't include any templates
  which I thought was part of the scope.  Maybe all the template
  changes are in Products.CMFPlone.

- What about plone.portlet.collection?

- What about Products.ATContentTypes' atct_topic_view?  Are we leaving
  that alone in favor of plone.app.collection?

- plone/app/contentlisting/catalog.py is using zLOG.  Isn't this
  deprecated in favor of python's logging module?

- plone/app/contentlisting/catalog.py looks like it's using log level
  INFO for something which might be inside an inner loop.  This should
  probably be DEBUG or else it will be too noisy.

- Definitely needs documentation along the lines of "If you want to
  customize ??? you can do ???".  I would consider this a blocker.

- I can't see any changes in the
  Plone/branches/plip9327-contentlisting history except cleaning up
  whitespace.  Am I missing something?  Is this only used in
  plone.app.search and plone.app.collection for now?

- There are failures for "bin/test -s Products.CMFPlone" that don't
  occur with buildout.cfg.  I'm betting this is because of the
  (possibly empty) branch of Plone and would be fixed on merge:

  Failure in test testDoUpgrades (Products.CMFPlone.tests.testMigrationTool.TestMigrationTool)
  Traceback (most recent call last):
    File "/usr/lib/python2.6/unittest.py", line 279, in run
      testMethod()
    File "plone-coredev.svn/src/Plone/Products/CMFPlone/tests/testMigrationTool.py", line 63, in testDoUpgrades
      self.assertEquals(last, current)
    File "/usr/lib/python2.6/unittest.py", line 350, in failUnlessEqual
      (msg or '%r != %r' % (first, second))
  AssertionError: ('4100',) != (u'4015',)
  
  Failure in test testListUpgradeSteps (Products.CMFPlone.tests.testMigrationTool.TestMigrationTool)
  Traceback (most recent call last):
    File "/usr/lib/python2.6/unittest.py", line 279, in run
      testMethod()
    File "plone-coredev.svn/src/Plone/Products/CMFPlone/tests/testMigrationTool.py", line 37, in testListUpgradeSteps
      self.failUnless(len(upgrades) == 0)
    File "/usr/lib/python2.6/unittest.py", line 325, in failUnless
      if not expr: raise self.failureException, msg
  AssertionError
  
  Error in test testHaveHead (Products.CMFPlone.tests.testS5.TestS5)
  Traceback (most recent call last):
    File "/usr/lib/python2.6/unittest.py", line 279, in run
      testMethod()
    File "plone-coredev.svn/src/Plone/Products/CMFPlone/tests/testS5.py", line 41, in testHaveHead
      del self.app.REQUEST.__annotations__
  AttributeError: HTTPRequest instance has no attribute '__annotations__'
  
  Error in test testNoHead (Products.CMFPlone.tests.testS5.TestS5)
  Traceback (most recent call last):
    File "/usr/lib/python2.6/unittest.py", line 279, in run
      testMethod()
    File "plone-coredev.svn/src/Plone/Products/CMFPlone/tests/testS5.py", line 29, in testNoHead
      del self.app.REQUEST.__annotations__
  AttributeError: HTTPRequest instance has no attribute '__annotations__'
  
      942/948 (99.4%)plone-coredev.svn/src/Plone/Products/CMFPlone/MigrationTool.py:115: UserWarning: Module _imaging was already imported from plone-coredev.svn/lib/python2.6/site-packages/PILwoTk-1.1.6.4-py2.6-linux-i686.egg/_imaging.so, but plone-coredev.svn/lib/python2.6/site-packages/PIL-1.1.7-py2.6-linux-i686.egg is being added to sys.path
    vars['PIL'] = get_dist('PIL').version

Conclusion
----------

Documentation is much improved but need some minor cleanup before we
can consider this done.  Please review the empty sections and add
content or remove as appropriate.  Please also address the note above
about the "folderListing" method call in the docs.

The changes to folder_listing are much welcomed, but I think they need
to be checked more thoroughly against existing support for passing in
content objects or brains using the folderContents TAL variable.

Further review is required but will have to wait until tests and the
instance can run.
