Repository: plone.app.theming
Branch: refs/heads/master
Date: 2015-03-19T15:20:38+01:00
Author: Vincent Fretin (vincentfretin) <vincent.fretin@gmail.com>
Commit: https://github.com/plone/plone.app.theming/commit/f5fe018a100022a8366b4329c56825272e9508b3

Add an error log if the subrequest failed (probably a relative xi:include) instead of silently returning None (and so having a xi:include returning nothing).

Conflicts:
	docs/HISTORY.rst

Files changed:
M docs/HISTORY.rst
M src/plone/app/theming/utils.py

diff --git a/docs/HISTORY.rst b/docs/HISTORY.rst
index 9d5aa6b..6aa7435 100644
--- a/docs/HISTORY.rst
+++ b/docs/HISTORY.rst
@@ -4,6 +4,11 @@ Changelog
 1.3.0 (unreleased)
 ------------------
 
+- Add an error log if the subrequest failed (probably a relative xi:include)
+  instead of silently returning None (and so having a xi:include returning
+  nothing).
+  [vincentfretin]
+
 - Fix transform to not affect the result when theming is disabled
   [datakurre]
 
diff --git a/src/plone/app/theming/utils.py b/src/plone/app/theming/utils.py
index b8850da..6cce4e4 100644
--- a/src/plone/app/theming/utils.py
+++ b/src/plone/app/theming/utils.py
@@ -1,3 +1,4 @@
+import logging
 import Globals
 
 import pkg_resources
@@ -48,6 +49,8 @@
 from Products.CMFCore.interfaces import ISiteRoot
 from Products.CMFPlone.utils import safe_unicode
 
+LOGGER = logging.getLogger('plone.app.theming')
+
 
 class NetworkResolver(etree.Resolver):
     """Resolver for network urls
@@ -117,6 +120,7 @@ def resolve(self, system_url, public_id, context):
 
         response = subrequest(system_url, root=root)
         if response.status != 200:
+            LOGGER.error("Couldn't resolve %s", system_url)
             return None
         result = response.getBody()
         content_type = response.headers.get('content-type')


