Repository: plone.app.contenttypes


Branch: refs/heads/master
Date: 2015-11-20T23:46:11-06:00
Author: vangheem (vangheem) <vangheem@gmail.com>
Commit: https://github.com/plone/plone.app.contenttypes/commit/9b20dc959d73bdc31d400b9893208333c82ce717

avoid AttributeError here. This is hard to pin point and harder to test. I am getting an error on a production site that needs this fix. It is weird and not reproducible in dev mode though. This is just more safe code so I am contributing this just to prevent others from having the same headache. Sorry for no test, I do not know how to make it break to be honest...

Files changed:
M CHANGES.rst
M plone/app/contenttypes/browser/folder.py

diff --git a/CHANGES.rst b/CHANGES.rst
index f39738f..76477e8 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -11,7 +11,7 @@ New:
 
 Fixes:
 
-- Fix potential acquisition issues with folder listings
+- Avoid AttributeError from potential acquisition issues with folder listings
   [vangheem]
 
 - Avoid AttributeError when trying to get the default_page of an item
diff --git a/plone/app/contenttypes/browser/folder.py b/plone/app/contenttypes/browser/folder.py
index cf950c3..7a949f2 100644
--- a/plone/app/contenttypes/browser/folder.py
+++ b/plone/app/contenttypes/browser/folder.py
@@ -64,8 +64,11 @@ def results(self, **kwargs):
         kwargs.setdefault('b_size', self.b_size)
         kwargs.setdefault('b_start', self.b_start)
 
-        results = aq_inner(self.context).restrictedTraverse(
-            '@@folderListing')(**kwargs)
+        listing = aq_inner(self.context).restrictedTraverse(
+            '@@folderListing', None)
+        if listing is None:
+            return []
+        results = listing(**kwargs)
         return results
 
     def batch(self):


