Repository: plone.app.layout
Branch: refs/heads/master
Date: 2015-02-11T21:13:29-06:00
Author: vangheem (vangheem) <vangheem@gmail.com>
Commit: https://github.com/plone/plone.app.layout/commit/5fbeaf76f547515ae6a2a2df184021cd270d6160

check that site_rss_items is actually set first, it is possible in some cases it will be None. This can cause a test failure

Files changed:
M plone/app/layout/links/viewlets.py

diff --git a/plone/app/layout/links/viewlets.py b/plone/app/layout/links/viewlets.py
index 555616a..238c61d 100644
--- a/plone/app/layout/links/viewlets.py
+++ b/plone/app/layout/links/viewlets.py
@@ -110,12 +110,13 @@ def update(self):
                     settings = registry.forInterface(ISiteSyndicationSettings)
                 except KeyError:
                     return
-                for uid in settings.site_rss_items:
-                    obj = uuidToObject(uid)
-                    if obj is not None:
-                        self.rsslinks.extend(self.getRssLinks(obj))
-                self.rsslinks.extend(self.getRssLinks(
-                    self.portal_state.portal()))
+                if settings.site_rss_items:
+                    for uid in settings.site_rss_items:
+                        obj = uuidToObject(uid)
+                        if obj is not None:
+                            self.rsslinks.extend(self.getRssLinks(obj))
+                    self.rsslinks.extend(self.getRssLinks(
+                        self.portal_state.portal()))
         else:
             if util.context_enabled():
                 self.rsslinks.extend(self.getRssLinks(self.context))


