Repository: plone.app.folder


Branch: refs/heads/master
Date: 2015-09-29T01:54:42+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.folder/commit/08e1c61b6bf84309fa8ae5469c6ba48492a04939

Fixed test in combination with Products.BTreeFolder2 2.13.4 and higher.

Here we have a folder with a `_tree` of None.  When asking this tree
for objectValues, we expected an AttributeError, but got a TypeError,
which is logical.

Files changed:
M CHANGES.rst
M src/plone/app/folder/tests/test_migration.py

diff --git a/CHANGES.rst b/CHANGES.rst
index 0d5bc48..2853f0f 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -4,6 +4,10 @@ Changelog
 1.1.1 (unreleased)
 ------------------
 
+- Fixed test in combination with Products.BTreeFolder2 2.13.4 and
+  higher.
+  [maurits]
+
 - Use registry lookup for types_use_view_action_in_listings.
   [esteele]
 
diff --git a/src/plone/app/folder/tests/test_migration.py b/src/plone/app/folder/tests/test_migration.py
index 29ade4b..399aec8 100644
--- a/src/plone/app/folder/tests/test_migration.py
+++ b/src/plone/app/folder/tests/test_migration.py
@@ -94,8 +94,10 @@ def testReverseMigrate(self):
         try:
             self.assertEqual(list(btree.objectValues()), [])
             self.assertEqual(list(btree.objectIds()), [])
-        except AttributeError:
+        except (AttributeError, TypeError):
             # BBB In Zope 2.13 this always raises AttributeError
+            # (Products.BTreeFolder2 2.13.3 or lower) or TypeError
+            # (Products.BTreeFolder2 2.13.4 or higher).
             pass
         self.assertEqual(
             btree._objects,


Repository: plone.app.folder


Branch: refs/heads/master
Date: 2015-09-29T02:02:05+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.folder/commit/01ef50f04c0d2ca9cbe49b750c9efb86f1bdd3a4

Removed part of test that was for Zope 2.12 or lower.

We were testing that we could ask a folder its object values or ids
after we migrated its btree to None.
In Zope 2.12 this returned an empty list.
In Zope 2.13 and higher this returns either an AttributeError
or a TypeError.
We only support 2.13, so it is not really interesting to check this.

Files changed:
M src/plone/app/folder/tests/test_migration.py

diff --git a/src/plone/app/folder/tests/test_migration.py b/src/plone/app/folder/tests/test_migration.py
index 399aec8..325808b 100644
--- a/src/plone/app/folder/tests/test_migration.py
+++ b/src/plone/app/folder/tests/test_migration.py
@@ -89,16 +89,6 @@ def testReverseMigrate(self):
         self.failUnless(hasattr(btree, '_tree'))
         self.failIf('_tree' in btree.__dict__)
         self.assertEqual(btree._tree, None)
-        # please note that the default adapter returns empty lists here
-        # while the partial one raises `AttributeErrors`
-        try:
-            self.assertEqual(list(btree.objectValues()), [])
-            self.assertEqual(list(btree.objectIds()), [])
-        except (AttributeError, TypeError):
-            # BBB In Zope 2.13 this always raises AttributeError
-            # (Products.BTreeFolder2 2.13.3 or lower) or TypeError
-            # (Products.BTreeFolder2 2.13.4 or higher).
-            pass
         self.assertEqual(
             btree._objects,
             (


